name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00

permissions:
  actions: write
  contents: read


jobs:
  clean:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 6
